# Generated by Django 6.0.7 on 2026-08-02 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SignalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("triggered_correctly", models.IntegerField(default=0)),
                ("triggered_falsely", models.IntegerField(default=0)),
                ("win_rate", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=64)),
                ("role", models.CharField(max_length=16)),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("watchlist", "Watchlist"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("file_name", models.CharField(max_length=120)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("date", models.CharField(blank=True, default="", max_length=32)),
                ("direction", models.CharField(blank=True, default="", max_length=32)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("conviction", models.CharField(blank=True, default="", max_length=16)),
                (
                    "entry_price",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("stop_loss", models.CharField(blank=True, default="", max_length=32)),
                ("exit_price", models.CharField(blank=True, default="", max_length=32)),
                ("targets", models.CharField(blank=True, default="", max_length=128)),
                ("outcome", models.CharField(blank=True, default="", max_length=64)),
                ("note", models.TextField(blank=True, default="")),
                ("rationale", models.TextField(blank=True, default="")),
                ("signals_used", models.TextField(blank=True, default="")),
                ("return_realized_pct", models.FloatField(blank=True, null=True)),
                ("raw", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "kind", "file_name"),
                        name="uniq_trade_per_user",
                    )
                ],
            },
        ),
    ]
