# Generated by Django 6.0.7 on 2026-08-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0002_chat_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="entry_zone",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="trade",
            name="horizon",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="trade",
            name="risk_reward",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="trade",
            name="targets",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
