# Generated by Django 6.0.7 on 2026-08-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0003_extra_trade_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateField(db_index=True)),
                ("mode", models.CharField(default="full", max_length=16)),
                ("signal_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailySignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scan_date", models.DateField(db_index=True)),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("direction", models.CharField(default="long", max_length=16)),
                ("entry_low", models.FloatField(blank=True, null=True)),
                ("entry_high", models.FloatField(blank=True, null=True)),
                ("tp1", models.FloatField(blank=True, null=True)),
                ("tp2", models.FloatField(blank=True, null=True)),
                ("stop_loss", models.FloatField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_signals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_date", "ticker"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "scan_date", "ticker"),
                        name="uniq_daily_signal",
                    )
                ],
            },
        ),
    ]
