# Generated by Django 6.0.7 on 2026-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_client_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="signallog",
            name="best_return_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signallog",
            name="evidence_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="signallog",
            name="mean_return_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signallog",
            name="median_return_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signallog",
            name="n_missing_return",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signallog",
            name="n_trades",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="signallog",
            name="total_return_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signallog",
            name="verdict",
            field=models.CharField(blank=True, default="insufficient", max_length=16),
        ),
        migrations.AddField(
            model_name="signallog",
            name="worst_return_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
